name: Development Build

on: 
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - develop
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # VUE_APP_SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: npm install and build
      run: |
        npm ci
        npm run build -- --mode dev
      env:
        CI: true
    - name: Deploy to Dev S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: 'dev.nicetohave.me'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-central-1'
        SOURCE_DIR: 'dist'
